version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: stg_locations
    columns:
      - name: location_id
        tests:
          - unique
          - not_null

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_supplies
    columns:
      - name: supply_uuid
        tests:
          - unique
          - not_null
