version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_ordered_at
        description: Date (UTC) of a customer's first order

      - name: last_ordered_at
        description: Date (UTC) of a customer's most recent order

      - name: count_lifetime_orders
        description: Count of the number of orders a customer has placed

      - name: lifetime_spend
        description: Total value of a customer's orders

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on order items

    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null

      - name: ordered_at
        description: Date (UTC) that the order was placed

      - name: order_cost
        description: Cost of supplies for the order

      - name: order_items_subtotal
        description: Total of order items

      - name: count_food_items
        description: Count of food items in order

      - name: count_drink_items
        description: Count of drink items in order

      - name: count_order_items
        description: Total count of items in order
